x-includes:
  node-version: "24"
  selenium-template: "compose-shared-selenium/docker-compose.yml"
  webserver-template: "compose-shared-nginx/compose.yml"
  database-template: "compose-shared-mariadb.yml"
  mailpit-template: "compose-shared-mailpit/compose.yml"

services:
  mysql:
    image: mariadb:11.8.8@sha256:24e76fcec8c003a0362d0dd53f4806e7e79458d7fdeaf47437760e19496f5a9c
  openemr:
    image: openemr/dev-php-fpm:8.3@sha256:543f8b1b9db0260c8238f5b9412a139dc29168fb59c8a3fe7dfad6cc99d09b4c
